# Generated by Django 4.1.7 on 2023-06-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='slug',
            field=models.SlugField(unique=True, unique_for_date='created'),
        ),
    ]
