# Generated by Django 4.1.7 on 2023-07-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='banner',
            field=models.ImageField(blank=True, help_text='A banner image for the post', null=True, upload_to=''),
        ),
    ]
