# Generated by Django 4.1.7 on 2023-07-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_contact_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='banner',
            field=models.ImageField(blank=True, help_text='A banner image for the post', null=True, upload_to='images/'),
        ),
    ]
