# Generated by Django 4.1.7 on 2023-07-20 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_contact_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contest',
        ),
    ]
